package com.vinsuite.controller;

import com.vinsuite.model.TestCase;
import com.vinsuite.service.qa.VisionAIService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/vision")
public class VisionAIController {

    @Autowired
    private VisionAIService visionAIService;

    @PostMapping(
        value = "/generate-ocr-testcases",
        consumes = "multipart/form-data"
    )
    public ResponseEntity<?> generateTestCasesFromImage(
        @RequestPart("image") MultipartFile image,
        @RequestPart("feature") String feature
    ) {
        try {
            System.out.println("📥 Received OCR request with feature: " + feature + " and image size: " + image.getSize());

            byte[] imageBytes = image.getBytes();
            List<TestCase> testCases = visionAIService.generateTestCasesFromImageAndFeature(imageBytes, feature);

            if (testCases == null || testCases.isEmpty()) {
                return ResponseEntity.status(HttpStatus.NO_CONTENT)
                        .body(Map.of("error", "No test cases generated by the AI."));
            }

            return ResponseEntity.ok(Map.of("testCases", testCases));
        } catch (Exception e) {
            e.printStackTrace();
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(Map.of("error", "Failed to generate test cases: " + e.getMessage()));
        }
    }
}
